---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-def
  labels:
    name: client-def
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.spring-test-ejem1: semver:~0.2
  namespace: client-def
spec:
  replicas: 3
  selector:
    matchLabels:
      name: client-def
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: client-def
    spec:
      containers:
      - image: rubru94/spring-test-ejem1:0.2.1
        name: spring-test-ejem1
        env:
        - name: CHARACTER
          value: "la app DEF."
        - name: SLEEP_TIME
          value: "3"
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
          limits:
            memory: "100Mi"
            cpu: "100m"
