apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: kube-system
spec:
  releaseName: kube-state-metrics
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: kube-state-metrics
    version: 2.6.4